package generator

import "github.com/orot/forge/internal/project"

// BasicFiles returns the default file set generated by `forge gen basic`.
func BasicFiles(p *project.Config) []FileSpec {
	return []FileSpec{
		{
			Path: "README.md",
			Content: "# " + p.Name + "\n\n" +
				p.Description + "\n",
		},
		{
			Path: "TODO.md",
			Content: "# TODO — " + p.Name + "\n\n" +
				"- [ ] Initial setup\n",
		},
		{
			Path:    ".gitignore",
			Content: defaultGitignore(p.Type),
		},
		{
			Path:    ".env.example",
			Content: "# Environment variables for " + p.Name + "\n",
		},
	}
}

func defaultGitignore(t string) string {
	common := "# Forge generated\n.forge/cache/\n.DS_Store\n.env\n"
	switch t {
	case "node", "next", "nest":
		return common + "node_modules/\ndist/\nbuild/\n.next/\ncoverage/\n*.log\n"
	case "go":
		return common + "bin/\n/dist/\n*.test\nvendor/\n"
	case "java":
		return common + "target/\nbuild/\n*.class\n*.jar\n"
	default:
		return common
	}
}
